version: 2

sources:
  - name: main
    tables:
      - name: owid_co2_data
        meta:
          dagster:
            asset_key: ["owid_co2_data"]
      - name: owid_energy_data
        meta:
          dagster:
            asset_key: ["owid_energy_data"]
