[project]
name = "datadex"
version = "1.0.0"
authors = [{ name = "David Gasquez" }]
dependencies = [
    "altair",
    "dagster-dbt",
    "dagster-duckdb-pandas",
    "dagster-duckdb-polars",
    "dagster",
    "datasets",
    "dbt-core",
    "dbt-duckdb",
    "duckdb",
    "frictionless",
    "huggingface_hub",
    "ipykernel",
    "ipywidgets",
    "matplotlib",
    "nbclient",
    "nbformat",
    "pyarrow",
    "python-slugify",
    "regex",
    "tenacity",
]

requires-python = ">=3.11, <=3.12"
readme = "README.md"
license = { text = "MIT" }

[project.urls]
Homepage = "https://davidgasquez.github.io/datadex/"
Changelog = "https://github.com/davidgasquez/datadex/commits/main/"
Issues = "https://github.com/davidgasquez/datadex/issues"
CI = "https://github.com/davidgasquez/datadex/actions"

[project.optional-dependencies]
dev = ["dagit", "ruff"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["datadex"]

[tool.setuptools.package-data]
"datadex" = ["../dbt/**"]

[tool.dagster]
module_name = "datadex"

[tool.ruff.lint.isort]
case-sensitive = true
combine-as-imports = true
length-sort = true
