project:
  type: website
  output-dir: .quarto/output
  preview:
    port: 5000

format:
  html:
    anchor-sections: true
    theme: litera

website:
  title: Datadex
  favicon: logo.svg
  repo-url: https://github.com/davidgasquez/datadex
  page-footer: Made with ❤ by David Gasquez
  search: false
  navbar:
    logo: logo.svg
    left:
      - text: Knowledge Base
        icon: book
        href: docs
        file: dbt
      - text: Datasets
        icon: box-seam
        href: https://huggingface.co/datonic
    tools:
      - icon: hexagon-fill
        href: https://datonic.io
      - icon: twitter
        href: https://twitter.com/davidgasquez
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/davidgasquez/datadex
          - text: Create an Issue
            url: https://github.com/davidgasquez/datadex/issues/new
