project:
  type: website
  output-dir: .quarto/output
  preview:
    port: 5000

format:
  html:
    anchor-sections: true
    theme: litera

website:
  title: Datadex
  favicon: logo.svg
  repo-url: https://github.com/davidgasquez/datadex
  repo-actions: [edit, issue]
  page-footer: Made with ❤️ by David Gasquez
  search: false
  navbar:
    logo: logo.svg
    left:
      - text: dbt Docs
        icon: sun
        file: dbt
      - text: Knowledge Base
        icon: book
        href: notebooks
      - text: Tutorial
        icon: bi-journal
        href: docs/tutorial.html
    tools:
      - icon: hexagon
        href: https://datonic.io
      - icon: twitter
        href: https://twitter.com/davidgasquez
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/davidgasquez/datadex
          - text: Create an Issue
            url: https://github.com/davidgasquez/datadex/issues/new
