name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    env:
      IUCN_REDLIST_TOKEN: ${{ secrets.IUCNREDLIST_TOKEN }}
      HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
      AEMET_API_TOKEN: ${{ secrets.AEMET_API_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip
      - uses: prefix-dev/setup-pixi@v0.8.0
        with:
          pixi-version: v0.27.1
          cache: true
      - name: Run
        run: |
          pixi run run