name: CI

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 10 * * 1"
  workflow_dispatch:

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    env:
      IUCN_REDLIST_TOKEN: ${{ secrets.IUCNREDLIST_TOKEN }}
      HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: pip
      - name: Install dependencies
        run: |
          pip install -e .
      - name: Run
        run: |
          make run
      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release
      - name: Render
        run: |
          make render
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: fbe814d4a37d3d3d7fcfeec0ab929ff6
          projectName: datadex
          directory: portal/.quarto/output
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
